package com.alibaba.druid.bvt.sql.postgresql.issues;

import com.alibaba.druid.DbType;
import com.alibaba.druid.sql.ast.SQLStatement;
import com.alibaba.druid.sql.parser.SQLParserUtils;
import com.alibaba.druid.sql.parser.SQLStatementParser;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Fix PostgreSQL parser failing on LIKE ? ESCAPE '\' syntax generated by JPA/Hibernate.
 * <p>
 * The PGLexer treated backslash as an escape character inside string literals,
 * which is incorrect for standard PostgreSQL (standard_conforming_strings = on since PG 9.1).
 * This caused '\' to be parsed as an escaped quote instead of a string containing a backslash.
 *
 * @see <a href="https://github.com/alibaba/druid/issues/6413">Issue #6413</a>
 */
public class Issue6413 {
    @Test
    public void test_like_escape_backslash() {
        // Exact SQL from the bug report (JPA-generated)
        String sql = "select rf1_0.id,rf1_0.name from real_functions rf1_0 "
                + "left join groups g1_0 on g1_0.id=rf1_0.group_id "
                + "where rf1_0.name like ? escape '\\' and g1_0.id=? fetch first ? rows only";

        for (DbType dbType : new DbType[]{DbType.postgresql, DbType.greenplum, DbType.edb}) {
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            List<SQLStatement> stmtList = parser.parseStatementList();
            assertEquals(1, stmtList.size());
            assertNotNull(stmtList.get(0));
        }
    }

    @Test
    public void test_like_escape_backslash_simple() {
        // Minimal reproduction case
        String sql = "select * from t where name like ? escape '\\'";
        for (DbType dbType : new DbType[]{DbType.postgresql, DbType.greenplum, DbType.edb}) {
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, dbType);
            List<SQLStatement> stmtList = parser.parseStatementList();
            assertEquals(1, stmtList.size());
        }
    }

    @Test
    public void test_like_escape_non_backslash_still_works() {
        // Other escape characters should still work
        for (String escapeChar : new String[]{"#", "!", "~"}) {
            String sql = "select * from t where name like ? escape '" + escapeChar + "'";
            SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
            List<SQLStatement> stmtList = parser.parseStatementList();
            assertEquals(1, stmtList.size());
        }
    }

    @Test
    public void test_string_with_backslash_in_pg() {
        // Standard PG strings with backslash should parse correctly
        String sql = "select * from t where name = '\\'";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
    }

    @Test
    public void test_string_with_double_backslash_in_pg() {
        // Double backslash in standard PG string
        String sql = "select * from t where name = '\\\\'";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
    }

    @Test
    public void test_like_escape_backslash_with_wall_filter() {
        // Verify it also works through WallProvider (the actual failure path in the bug report)
        String sql = "select rf1_0.id from real_functions rf1_0 "
                + "where rf1_0.name like ? escape '\\' and rf1_0.group_id=? fetch first ? rows only";

        // Parsing should succeed (WallFilter calls parser internally)
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
        String output = stmtList.get(0).toString();
        assertTrue(output.contains("ESCAPE"));
    }

    @Test
    public void test_not_like_escape_backslash() {
        // NOT LIKE with backslash ESCAPE should also work
        String sql = "select * from t where name not like ? escape '\\'";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
    }

    @Test
    public void test_ilike_with_backslash_string() {
        // ILIKE (PG-specific) with backslash in string pattern
        String sql = "select * from t where name ilike '%test\\%'";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
    }

    @Test
    public void test_pg_double_single_quote_still_works() {
        // PG standard '' escape for single quotes must still work
        String sql = "select * from t where name = 'it''s a test'";
        SQLStatementParser parser = SQLParserUtils.createSQLStatementParser(sql, DbType.postgresql);
        List<SQLStatement> stmtList = parser.parseStatementList();
        assertEquals(1, stmtList.size());
    }
}
