DROP AGGREGATE dbo.Concatenate;
DROP APPLICATION ROLE rolename
DROP ASSEMBLY Helloworld ;
DROP ASYMMETRIC KEY MirandaXAsymKey6;
DROP AVAILABILITY GROUP group_name
DROP BROKER PRIORITY InitiatorAToTargetPriority
DROP CERTIFICATE certificate_name
DROP COLUMN ENCRYPTION KEY MyCEK;
DROP COLUMN MASTER KEY MyCMK;
DROP CONTRACT
    [//Adventure-Works.com/Expenses/ExpenseSubmission] ;
DROP CREDENTIAL Saddles;
DROP CRYPTOGRAPHIC PROVIDER provider_name
DROP CRYPTOGRAPHIC PROVIDER SecurityProvider;  
DROP CRYPTOGRAPHIC PROVIDER SecurityProvider;
GO
DROP DATABASE Sales;
DROP DATABASE Sales, NewSales;
DROP DATABASE AUDIT SPECIFICATION HIPAA_Audit_DB_Specification;
DROP DATABASE ENCRYPTION KEY;
DROP DATABASE SCOPED CREDENTIAL AppCred;
DROP DEFAULT datedflt;
DROP DEFAULT IF EXISTS datedflt;
DROP ENDPOINT sql_endpoint;
DROP EXTERNAL DATA SOURCE mydatasource;
DROP EXTERNAL FILE FORMAT myfileformat;
DROP EXTERNAL LIBRARY ggplot2 AUTHORIZATION user_name;
DROP EXTERNAL RESOURCE POOL ex_pool;
GO
ALTER RESOURCE GOVERNOR RECONFIGURE;
GO
DROP EXTERNAL TABLE SalesPerson;
DROP EXTERNAL TABLE dbo.SalesPerson;
DROP EXTERNAL TABLE EasternDivision.dbo.SalesPerson;
DROP EXTERNAL TABLE EasternDivision.dbo.SalesPerson;
DROP EVENT NOTIFICATION NotifyALTER_T1
ON DATABASE;
DROP EVENT SESSION evt_spin_lock_diagnosis
ON SERVER;
DROP FULLTEXT INDEX ON HumanResources.JobCandidate;
DROP FULLTEXT STOPLIST myStoplist;
DROP FUNCTION Sales.fn_SalesByStore;
DROP LOGIN WilliJo;
GO
DROP MASTER KEY;
DROP MESSAGE TYPE [//Adventure-Works.com/Expenses/SubmitExpense] ;
DROP PARTITION FUNCTION myRangePF;
DROP PARTITION SCHEME myRangePS1;
DROP PROCEDURE dbo.uspMyProc;
DROP QUEUE ExpenseQueue ;
DROP REMOTE SERVICE BINDING APBinding ;
DROP RESOURCE POOL big_pool;
GO
ALTER RESOURCE GOVERNOR RECONFIGURE;
GO
DROP ROLE purchasing;
GO
DROP ROUTE ExpenseRoute ;
DROP ROUTE ExpenseRoute ;
DROP SCHEMA schema_name
DROP SEARCH PROPERTY LIST JobCandidateProperties;
GO
DROP SECURITY POLICY secPolicy;
DROP SEQUENCE CountBy1 ;
DROP SERVER AUDIT HIPAA_Audit;
DROP SERVER AUDIT SPECIFICATION HIPAA_Audit_Specification;
DROP SERVER ROLE purchasing;
GO
DROP SERVICE [//Adventure-Works.com/Expenses] ;
DROP SIGNATURE FROM HumanResources.uspUpdateEmployeeLogin
    BY CERTIFICATE HumanResourcesDP;
DROP STATISTICS Purchasing.Vendor.VendorCredit, Sales.SalesOrderHeader.CustomerTotal;
DROP SYMMETRIC KEY GailSammamishKey6;
DROP SYNONYM MyProduct;
DROP TABLE AdventureWorks2012.dbo.SalesPerson2 ;
DROP TABLE #temptable;
DROP TABLE IF EXISTS T1;
DROP TRIGGER employee_insupd;
DROP TYPE ssn ;
DROP USER AbolrousHazem;
GO
DROP VIEW dbo.Reorder ;
GO
DROP WORKLOAD GROUP adhoc;
GO
ALTER RESOURCE GOVERNOR RECONFIGURE;
GO
DROP XML SCHEMA COLLECTION ManuInstructionsSchemaCollection;
GO
