ALTER LOGIN Mary5 ENABLE;  
ALTER LOGIN Mary5 WITH PASSWORD = '<enterStrongPasswordHere>';
ALTER LOGIN Mary5 WITH NAME = John2;
ALTER LOGIN John2 WITH CREDENTIAL = Custodian04;
ALTER LOGIN Mary5
ADD CREDENTIAL EKMProvider1;
GO
ALTER LOGIN [Mary5] WITH PASSWORD = '****' UNLOCK ;

GO
ALTER LOGIN [Mary5] WITH CHECK_POLICY = OFF;
ALTER LOGIN [Mary5] WITH CHECK_POLICY = ON;
GO
ALTER LOGIN TestUser WITH
PASSWORD = 0x01000CF35567C60BFB41EBDE4CF700A985A13D773D6B45B90900 HASHED ;
GO
ALTER LOGIN Login1
ADD CREDENTIAL CredentialForEKM;
ALTER LOGIN Login1
WITH CREDENTIAL = AlterEgo;
GO

CREATE LOGIN login_name WITH PASSWORD = '<enterStrongPasswordHere>';
GO
CREATE LOGIN login_name WITH PASSWORD = '<enterStrongPasswordHere>' MUST_CHANGE;
GO
CREATE LOGIN login_name WITH PASSWORD = '<enterStrongPasswordHere>',
    CREDENTIAL = credentialName;
GO
USE MASTER;
CREATE CERTIFICATE CertificateName
    WITH SUBJECT = '<login_name> certificate in master database',
    EXPIRY_DATE = '12/05/2025';
GO
CREATE LOGIN login_name FROM CERTIFICATE certificateName;
GO
CREATE LOGIN [domainName\login_name] FROM WINDOWS;
GO
CREATE LOGIN TestLogin
WITH PASSWORD = 'SuperSecret52&&', SID = 0x241C11948AEEB749B0D22646DB1A19F2;


CREATE LOGIN Mary7 WITH PASSWORD = 'A2c3456$#' ;

CREATE LOGIN Mary8 WITH PASSWORD = 'A2c3456$#' MUST_CHANGE,
CHECK_EXPIRATION = ON,
CHECK_POLICY = ON;
CREATE LOGIN [Contoso\Mary] FROM WINDOWS;
GO
