
CREATE TABLE `sample` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `VALUE` text,
  `TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PK_SAMPLE` (`ID`),
  KEY `TIME` (`TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='A sample table.';
