CREATE TABLE druid_weburi (
	id bigint(20) AUTO_INCREMENT NOT NULL, 
	domain varchar(45) NOT NULL, 
	app varchar(45) NOT NULL, 
	cluster varchar(45) NOT NULL, 
	host varchar(128), 
	pid int(10) NOT NULL, 
	collectTime datetime NOT NULL, 
	uri varchar(256), 
	runningCount int(10), 
	concurrentMax int(10), 
	requestCount bigint(20), 
	requestTimeNano bigint(20), 
	jdbcFetchRowCount bigint(20), 
	jdbcFetchRowPeak bigint(20), 
	jdbcUpdateCount bigint(20), 
	jdbcUpdatePeak bigint(20), 
	jdbcExecuteCount bigint(20), 
	jdbcExecuteErrorCount bigint(20), 
	jdbcExecutePeak bigint(20), 
	jdbcExecuteTimeNano bigint(20), 
	jdbcCommitCount bigint(20), 
	jdbcRollbackCount bigint(20), 
	jdbcPoolConnectionOpenCount bigint(20), 
	jdbcPoolConnectionCloseCount bigint(20), 
	jdbcResultSetOpenCount bigint(20), 
	jdbcResultSetCloseCount bigint(20), 
	errorCount bigint(20), 
	lastAccessTime datetime, 
	h1 bigint(20), 
	h10 bigint(20), 
	h100 bigint(20), 
	h1000 bigint(20), 
	h10000 int(10), 
	h100000 int(10), 
	h1000000 int(10), 
	hmore int(10), 
	PRIMARY KEY (id)
);

CREATE INDEX druid_weburi_index ON druid_weburi (collectTime, domain, app);