SELECT TO_DATE('01.01.2012') FROM DUAL
SELECT TO_DATE('01.01.2012', 'dd.mm.yyyy') FROM DUAL
SELECT TO_DATE('01' || '.01.2012', 'dd.mm.yyyy') FROM DUAL
SELECT TO_DATE('01.' || (NQUATER*3 - 2) || '.' || NRYEAR, 'DD.MM.YYYY') FROM DUAL
SELECT LAST_DAY(TO_DATE('01.' || (NQUATER*3 - 2) || '.' || NRYEAR, 'DD.MM.YYYY')) FROM DUAL
SELECT TO_CHAR(LAST_DAY(TO_DATE('01.' || (NQUATER*3 - 2) || '.' || NRYEAR, 'DD.MM.YYYY')),'DD') FROM DUAL